spring.application.name=testingApp
spring.datasource.url=jdbc:mysql://localhost:3306/unit_test_springboot?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto = update

server.port=8082

